apiVersion: v1
kind: Template
labels:
  template: fabric8-dev-recommender
metadata:
  name: fabric8-dev-recommender
  annotations:
    description: fabric8-dev-recommender
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: fabric8-dev-recommender
    name: fabric8-dev-recommender
  spec:
    selector:
      service: fabric8-dev-recommender
    template:
      metadata:
        labels:
          service: fabric8-dev-recommender
      spec:
        containers:
        - image: "arunkumars08/ops-portal-v2:latest"
          name: fabric8-dev-recommender
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${REPLICAS}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: fabric8-dev-recommender
    name: fabric8-dev-recommender
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: fabric8-dev-recommender
- apiVersion: v1
  kind: Route
  metadata:
    name: fabric8-dev-recommender
  spec:
    to:
      kind: Service
      name: fabric8-dev-recommender

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-dev-recommender"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"
